stages:
  - publish

docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: publish
  dependencies:
    - build
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  script:
    - docker build --pull -t "jayaneetha/images:zeta-web-backend" .
    - docker push "jayaneetha/images:zeta-web-backend"
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
