# Generated by Django 4.0.3 on 2022-03-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
